### ISSUE TITLE
What teamcity versions are available?

### ISSUE THREAD

**Issue by schancel** [JetBrains/teamcity-sdk-maven-plugin#12]
Is 10.0 the last release to use?  Or is 2017.2 available as well?  How do you find out?

**Comment by nskvortsov** [comment]
You can always navigate to repository, containing maven artifacts of TeamCity API. E.g., for server-side APIs available versions are listed here: http://download.jetbrains.com/teamcity-repository/org/jetbrains/teamcity/server-api/
