### ISSUE TITLE
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): :

### ISSUE THREAD

**Issue by pragal18** [JetBrains/teamcity-sdk-maven-plugin#14]
Hi, 

I tried to execute this command :
mvn org.apache.maven.plugins:maven-archetype-plugin:2.4:generate \
  -DarchetypeRepository=http://download.jetbrains.com/teamcity-repository \
  -DarchetypeArtifactId=teamcity-server-plugin \
  -DarchetypeGroupId=org.jetbrains.teamcity.archetypes \
  -DarchetypeVersion=RELEASE -DteamcityVersion=10.0 \

I get this :

Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): 7:   -DarchetypeRepository=http://download.jetbrains.com/team
city-repository \
  -DarchetypeArtifactId=teamcity-server-plugin \
  -DarchetypeGroupId=org.jetbrains.teamcity.archetypes \
  -DarchetypeVersion=RELEASE -DteamcityVersion=10.0 \
Choose archetype:
   Your filter doesn't match any archetype (hint: enter to return to initial list)
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): : Choose archetype:
   Your filter doesn't match any archetype (hint: enter to return to initial list)
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): : Choose archetype:
   Your filter doesn't match any archetype (hint: enter to return to initial list)
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): : Choose archetype:
   Your filter doesn't match any archetype (hint: enter to return to initial list)
Choose a number or apply filter (format: [groupId:]artifactId, case sensitive contains): :

How should I go about from here. I tried typing in the values. It keeps repeating the same thing . Kindly help me. 

Thank you.

**Comment by nskvortsov** [comment]
Hi,
What maven version do you use?

вт, 30 окт. 2018 г., 14:43 pragal18 <notifications@github.com>:

**Comment by pragal18** [comment]
Thank you for quick response.

Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Maven home: C:\Users\GC2LAKS\Desktop\apache-maven-3.5.4\bin\..
Java version: 1.8.0_171, vendor: Oracle Corporation, runtime: C:\Program Files\Java\1.8.0_171
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "windows"

**Comment by nskvortsov** [comment]
please, append `-X` flag to the command to enable Maven debug output and attach resulting log (or upload it as gist and attach a link)

**Comment by pragal18** [comment]
[tcsdkmavenplugin.log](https://github.com/JetBrains/teamcity-sdk-maven-plugin/files/2529755/tcsdkmavenplugin.log)

**Comment by nskvortsov** [comment]
@pragal18 looks like, there are some errors in command line escaping. 
Please, try the command using single line, without any escaped newlines.

**Comment by nskvortsov** [comment]
I have updated the  [quick start](https://github.com/JetBrains/teamcity-sdk-maven-plugin/wiki/Developing-TeamCity-plugin) page accordingly
